### ISSUE TITLE
Error on saving file with symbolic link

### ISSUE THREAD

**Issue by nuomi1** [mohakapt/Stringz#4] opened 2020-12-24 11:31 UTC
I use symbolic link in `Localizable.strings` such as `../../../xxx-l10n/Localizable/zh-Hans.lproj/Localizable.strings`, but Stringz overwrites the file on saving.

**Comment by mohakapt** [comment] 2020-12-24 19:34
I couldn't reproduce the issue, It would be super helpful If you can create a sample app with a "soft link" so i can use it for debug.

**Comment by nuomi1** [comment] 2020-12-25 15:10
> I couldn't reproduce the issue, It would be super helpful If you can create a sample app with a "soft link" so i can use it for debug.

https://github.com/nuomi1/Timer/tree/feature/stringz-test

**Comment by nuomi1** [comment] 2020-12-25 15:14
Sorry, it's 'symbolic link'.

**Comment by mohakapt** [comment] 2020-12-25 16:32
Thanks for creating the example app, I will use it to debug Stringz and hopefully fix the issue.

**Comment by mohakapt** [comment] 2020-12-28 18:32
I just released a fix for this bug in the new version (v0.4.2). Please check it out.

**Comment by nuomi1** [comment] 2020-12-29 01:02
> I just released a fix for this bug in the new version (v0.4.2). Please check it out.

It's OK, thanks.

**Closed** 2021-01-06 11:21 UTC
Labels: bug
